name: "Build Setup"
description: "Setup Android Environment"

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v2

    - name: Setup Android
      uses: android-actions/setup-android@v3

    - name: Cache Gradle and wrapper
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
